// <auto-generated />
using System;
using EzFit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EzFit.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260804180127_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EzFit.Entities.ActivityData", b =>
                {
                    b.Property<int>("EntryId")
                        .HasColumnType("int");

                    b.Property<int?>("AvgHr")
                        .HasColumnType("int");

                    b.Property<decimal?>("DistanceKm")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("DurationMin")
                        .HasColumnType("int");

                    b.Property<decimal?>("ElevationM")
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("Kcal")
                        .HasColumnType("int");

                    b.Property<int?>("MaxHr")
                        .HasColumnType("int");

                    b.Property<int?>("Steps")
                        .HasColumnType("int");

                    b.HasKey("EntryId");

                    b.ToTable("ActivityData");
                });

            modelBuilder.Entity("EzFit.Entities.Day", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("Days");
                });

            modelBuilder.Entity("EzFit.Entities.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiRawResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RawText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("EzFit.Entities.NutritionData", b =>
                {
                    b.Property<int>("EntryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Carbs")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("Fats")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("Kcal")
                        .HasColumnType("int");

                    b.Property<decimal>("Protein")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("EntryId");

                    b.ToTable("NutritionData");
                });

            modelBuilder.Entity("EzFit.Entities.SleepData", b =>
                {
                    b.Property<int>("EntryId")
                        .HasColumnType("int");

                    b.Property<int?>("DeepMin")
                        .HasColumnType("int");

                    b.Property<int?>("LightMin")
                        .HasColumnType("int");

                    b.Property<int?>("RemMin")
                        .HasColumnType("int");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<int>("TotalMin")
                        .HasColumnType("int");

                    b.HasKey("EntryId");

                    b.ToTable("SleepData");
                });

            modelBuilder.Entity("EzFit.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EzFit.Entities.UserProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CarbsTarget")
                        .HasColumnType("int");

                    b.Property<int>("FatsTarget")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("HeightCm")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("KcalTarget")
                        .HasColumnType("int");

                    b.Property<int>("ProteinTarget")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("EzFit.Entities.ActivityData", b =>
                {
                    b.HasOne("EzFit.Entities.Entry", "Entry")
                        .WithOne("ActivityData")
                        .HasForeignKey("EzFit.Entities.ActivityData", "EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("EzFit.Entities.Day", b =>
                {
                    b.HasOne("EzFit.Entities.User", "User")
                        .WithMany("Days")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EzFit.Entities.Entry", b =>
                {
                    b.HasOne("EzFit.Entities.Day", "Day")
                        .WithMany("Entries")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");
                });

            modelBuilder.Entity("EzFit.Entities.NutritionData", b =>
                {
                    b.HasOne("EzFit.Entities.Entry", "Entry")
                        .WithOne("NutritionData")
                        .HasForeignKey("EzFit.Entities.NutritionData", "EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("EzFit.Entities.SleepData", b =>
                {
                    b.HasOne("EzFit.Entities.Entry", "Entry")
                        .WithOne("SleepData")
                        .HasForeignKey("EzFit.Entities.SleepData", "EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("EzFit.Entities.UserProfile", b =>
                {
                    b.HasOne("EzFit.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("EzFit.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EzFit.Entities.Day", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("EzFit.Entities.Entry", b =>
                {
                    b.Navigation("ActivityData");

                    b.Navigation("NutritionData");

                    b.Navigation("SleepData");
                });

            modelBuilder.Entity("EzFit.Entities.User", b =>
                {
                    b.Navigation("Days");

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
